### ISSUE TITLE
Implement serde Serialization for Rating

### ISSUE THREAD

**Issue by kellenff** [DataWraith/bbt#1]
I'd like to return a `Rating` in a Json struct. I can submit a pull request if preferred

**Comment by DataWraith** [comment]
Hi, yes, a pull request for that would be appreciated.

You probably noticed it already, but `Rating` stores `sigma` and `sigma_sq` redundantly for convenience. You might want to ignore `sigma_sq` when serializing the Rating and reconstruct it when deserializing (if that's possible with serde -- I'm not too familiar with it).

**Comment by kellenff** [comment]
Yes, I think that'd make sense. I believe that's definitely doable with `serde`, but I'll look into it more and submit a pull request.
